start_log: true # flag to automatically start logging joint_states during trajectory execution.

binary_logger:
  num_worker_threads: 10

  # manager_name: name of the nodlet manager (need to be equal to the name in the launch file)
  manager_name: 'binary_logger'

  # Type of the topic that need to be logged (supported JointState, Imu, PoseStamped, WrenchStamped, Float64MultiArray)
  topic_type:
    - 'JointState'

  JointState:
    # List of the topic to be acquired
    topic_names:
      - '/ur10/joint_states'  # put the joint_states topic with position, velocity and effort information

    # Maximum acquisition time (to be specified for each topic)
    duration:
      - 400 #[s]

    # Message decimation (to be specified for each topic)
    decimation:
      - 1

