group_name: "ur10"
rescale: false
meto_cfg:
  acceleration_scaling: 1.0
  speed_scaling: 1.0
  verbose: true
  urdf_param: "robot_description"
  urdf_name: "cybersort"
  trajectory_namespace: "ident_trj"
  controller_joint_names: 
  - ur10_shoulder_pan_joint
  - ur10_shoulder_lift_joint
  - ur10_elbow_joint
  - ur10_wrist_1_joint
  - ur10_wrist_2_joint
  - ur10_wrist_3_joint

    
  opt_cfg:
    stage1_duration: 10
    region_stage2: 0
    point_per_region: 5
    trials: 3
  filter:
    frequency: 50
    sample_period: 0.008